name: Shut
version: '${project.version}'
main: com.mailo.shut.Main
api-version: '1.13'
authors:
  - Harly47
  - Fmarco98
  - ELPAKISTANO (il sacco da boxe)
description: This plugin is used to teleport people randomly
commands:
  shutmenu:
    description: Opens the plugin menu
    aliases:
      - gallina
  shut:
    description: Main command of the plugin
    aliases:
      - shutdown